FROM python:3.13-slim

WORKDIR /app

#So Python should search inside /app(container) to find:
ENV PYTHONPATH=/app

COPY apps/requirement_apps.txt .

#After copying, inside container it becomes:/app/requirement_apps.txt
RUN pip install --no-cache-dir -r requirement_apps.txt

#copy all file
COPY . .

EXPOSE 8501 

CMD [ "streamlit","run","apps/streamlit_app.py","--server.port=8501","--server.address=0.0.0.0" ]